-- CHECK WHETHER THE TABLE 'ORDERS' CONTAINS ANY DUPLICATE ROWS

SELECT 
	OrderID,
	COUNT(*) OVER(PARTITION BY OrderID) checkPK
FROM Sales.Orders

SELECT 
	OrderID,
	COUNT(*) OVER(PARTITION BY OrderID) checkPK
FROM Sales.OrdersArchive