-- FIND THE AVG SALES ACROSS ALL ORDERS
-- AND FOND THE AVERAGE SALES FOR EACH PRODCUT
-- ADDITIONALLY PROVIDE DETAILS SUCH ORDR id,ORDER DATE

SELECT
	OrderID,
	OrderDate,
	Sales,
AVG(Sales) OVER () AvgSales,
AVG(Sales) OVER(PARTITION BY ProductID) AvgSaelsByProduct
FROM Sales.Orders