-- FIND THE AVERAGE SCORES OF CUSTOMERS
-- ADDITIONALLY PROVIDE DETAILS SUCH CUSTOMERID AN LASTNAME

SELECT 
	CustomerID,
	LastName,
	Score,
COALESCE(Score,0)  CUSTOMERSCORE,
AVG(Score) OVER() AVGSCORE,
AVG(COALESCE(Score,0) ) OVER() AVGSCORE

FROM Sales.Customers