--FIND THE ALL ORDERS WHERE SALES ARE HIGHER THAN THE AVERAGE SALES ACROSSS ALL ORDERS
SELECT *
FROM(
SELECT
	OrderID,
	ProductID,
	Sales,
	AVG(Sales) OVER() Avgsales
FROM Sales.Orders) t WHERE Sales > Avgsales