-- FIND THE DEVIATION OF EACH SALES FROM THE MINIMUM AND MAXIMUM SALES AMOUNTS
SELECT  
OrderID,
ProductID,

MIN(Sales) OVER(PARTITION BY ProductID) LOWSALESBYPRODUCT,
MAX(Sales) OVER(PARTITION BY ProductID) HIGHSALESBYPRODUCT,
Sales - MIN(Sales) OVER() DeviationFromMIN,
MAX(Sales)OVER() -  Sales  DeviationFromMAX

FROM Sales.Orders